package com.br.product.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "produto")
public class Product {
    @DynamoDBHashKey(attributeName = "produtoId")
    @DynamoDBAutoGeneratedKey
    private String produtoId;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private Double preco;

    public String getProdutoId() {
        return produtoId;
    }

    public void setProdutoId(String produtoId) {
        this.produtoId = produtoId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getPreco() {
        return preco;
    }

    public void setPreco(Double preco) {
        this.preco = preco;
    }

    public Product(String produtoId, String name, Double preco) {
        this.produtoId = produtoId;
        this.name = name;
        this.preco = preco;
    }

    public Product() {

    }
}
